// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.Fee.Services.Student.Identity.API.Data;

namespace Student.Identity.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Microsoft.Fee.Services.Student.Identity.API.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("IDNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<decimal>("Request")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.Fee.Services.Student.Identity.API.Models.EducationLevel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EducationLevels");

                    b.HasData(
                        new
                        {
                            Id = "LP",
                            Level = "Lower Primary"
                        },
                        new
                        {
                            Id = "UP",
                            Level = "Upper Primary"
                        },
                        new
                        {
                            Id = "PM",
                            Level = "Primary"
                        },
                        new
                        {
                            Id = "SN",
                            Level = "Secondary"
                        },
                        new
                        {
                            Id = "VC",
                            Level = "Vocational"
                        },
                        new
                        {
                            Id = "CL",
                            Level = "College"
                        },
                        new
                        {
                            Id = "UV",
                            Level = "University"
                        });
                });

            modelBuilder.Entity("Microsoft.Fee.Services.Student.Identity.API.Models.Hobby", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.HasKey("Id");

                    b.ToTable("Hobby");

                    b.HasData(
                        new
                        {
                            Id = "AT",
                            Name = "Art"
                        },
                        new
                        {
                            Id = "CT",
                            Name = "Chatting"
                        },
                        new
                        {
                            Id = "MU",
                            Name = "Makeup"
                        },
                        new
                        {
                            Id = "SM",
                            Name = "Social media"
                        },
                        new
                        {
                            Id = "RI",
                            Name = "Reading"
                        },
                        new
                        {
                            Id = "FD",
                            Name = "Fashion design"
                        },
                        new
                        {
                            Id = "FA",
                            Name = "Farming"
                        });
                });

            modelBuilder.Entity("Microsoft.Fee.Services.Student.Identity.API.Models.Location", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            Id = "001",
                            County = "Mombasa"
                        },
                        new
                        {
                            Id = "002",
                            County = "Kwale"
                        },
                        new
                        {
                            Id = "003",
                            County = "Kilifi"
                        },
                        new
                        {
                            Id = "004",
                            County = "Tana River"
                        },
                        new
                        {
                            Id = "005",
                            County = "Lamu"
                        },
                        new
                        {
                            Id = "006",
                            County = "Taita/Taveta"
                        },
                        new
                        {
                            Id = "007",
                            County = "Garissa"
                        },
                        new
                        {
                            Id = "008",
                            County = "Wajir"
                        },
                        new
                        {
                            Id = "009",
                            County = "Mandera"
                        },
                        new
                        {
                            Id = "010",
                            County = "Marsabit"
                        },
                        new
                        {
                            Id = "011",
                            County = "Isiolo"
                        },
                        new
                        {
                            Id = "012",
                            County = "Meru"
                        },
                        new
                        {
                            Id = "013",
                            County = "Tharaka-Nithi"
                        },
                        new
                        {
                            Id = "014",
                            County = "Embu"
                        });
                });

            modelBuilder.Entity("Microsoft.Fee.Services.Student.Identity.API.Models.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateofBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EducationLevelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HobbyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<string>("SchoolId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EducationLevelId");

                    b.HasIndex("HobbyId");

                    b.HasIndex("LocationId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Profile");

                    b.HasData(
                        new
                        {
                            Id = new Guid("397026a7-2ea7-4f35-84ac-733806cc7ab9"),
                            DateofBirth = new DateTime(2005, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EducationLevelId = "PM",
                            HobbyId = "MU",
                            LocationId = "010",
                            PaymentType = 0,
                            SchoolId = "HIS"
                        },
                        new
                        {
                            Id = new Guid("48c334b5-038d-4733-9ebe-aec342dbd480"),
                            DateofBirth = new DateTime(1985, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EducationLevelId = "UV",
                            HobbyId = "FA",
                            LocationId = "014",
                            PaymentType = 0,
                            SchoolId = "TIS"
                        });
                });

            modelBuilder.Entity("Microsoft.Fee.Services.Student.Identity.API.Models.School", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EducationLevelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EducationLevelId");

                    b.HasIndex("LocationId");

                    b.ToTable("School");

                    b.HasData(
                        new
                        {
                            Id = "HIS",
                            EducationLevelId = "PM",
                            LocationId = "001",
                            Name = "How in School"
                        },
                        new
                        {
                            Id = "WIS",
                            EducationLevelId = "SN",
                            LocationId = "013",
                            Name = "Where in School"
                        },
                        new
                        {
                            Id = "THS",
                            EducationLevelId = "VC",
                            LocationId = "008",
                            Name = "That School"
                        },
                        new
                        {
                            Id = "WHS",
                            EducationLevelId = "CL",
                            LocationId = "005",
                            Name = "Which School"
                        },
                        new
                        {
                            Id = "TIS",
                            EducationLevelId = "UV",
                            LocationId = "005",
                            Name = "This School"
                        });
                });

            modelBuilder.Entity("Microsoft.Fee.Services.Student.Identity.API.Models.Timeline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<string>("SchoolId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Timeline");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b61360c7-8530-4c71-b7f7-eafeac7d2062"),
                            Description = "Qqwertyuioplkjhgfdsazxcvbnm.",
                            Period = 5,
                            SchoolId = "HIS"
                        },
                        new
                        {
                            Id = new Guid("61773c06-7621-4548-8efb-d348c64fc079"),
                            Description = "Qqwertyuioplkjhgfdsazxcvbnm.",
                            Period = 5,
                            SchoolId = "TIS"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.Fee.Services.Student.Identity.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.Fee.Services.Student.Identity.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.Fee.Services.Student.Identity.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.Fee.Services.Student.Identity.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.Fee.Services.Student.Identity.API.Models.Profile", b =>
                {
                    b.HasOne("Microsoft.Fee.Services.Student.Identity.API.Models.EducationLevel", "EducationLevel")
                        .WithMany("Profiles")
                        .HasForeignKey("EducationLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.Fee.Services.Student.Identity.API.Models.Hobby", "Hobby")
                        .WithMany("Profiles")
                        .HasForeignKey("HobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.Fee.Services.Student.Identity.API.Models.Location", "Location")
                        .WithMany("Profiles")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.Fee.Services.Student.Identity.API.Models.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EducationLevel");

                    b.Navigation("Hobby");

                    b.Navigation("Location");

                    b.Navigation("School");
                });

            modelBuilder.Entity("Microsoft.Fee.Services.Student.Identity.API.Models.School", b =>
                {
                    b.HasOne("Microsoft.Fee.Services.Student.Identity.API.Models.EducationLevel", "EducationLevel")
                        .WithMany("Schools")
                        .HasForeignKey("EducationLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.Fee.Services.Student.Identity.API.Models.Location", "Location")
                        .WithMany("Schools")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationLevel");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Microsoft.Fee.Services.Student.Identity.API.Models.Timeline", b =>
                {
                    b.HasOne("Microsoft.Fee.Services.Student.Identity.API.Models.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Microsoft.Fee.Services.Student.Identity.API.Models.EducationLevel", b =>
                {
                    b.Navigation("Profiles");

                    b.Navigation("Schools");
                });

            modelBuilder.Entity("Microsoft.Fee.Services.Student.Identity.API.Models.Hobby", b =>
                {
                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("Microsoft.Fee.Services.Student.Identity.API.Models.Location", b =>
                {
                    b.Navigation("Profiles");

                    b.Navigation("Schools");
                });
#pragma warning restore 612, 618
        }
    }
}
