version: '3.4'

services:
  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"

  sqldata:
    user: root
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - fee-sqldata:/var/opt/mssql

  nosqldata:
    ports:
      - "27017:27017"
    volumes:
      - fee-nosqldata:/data/db

  basketdata:
    ports:
      - "6379:6379"
    volumes:
      - fee-basketdata:/data

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  corporatesponsoridentity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - SponsorSpaClient=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5225
      - XamarinCallback=http://${FEE_PROD_EXTERNAL_DNS_NAME_OR_IP}:5227/xamarincallback
      - ConnectionString=${FEE_AZURE_SPONSORIDENTITY_DB:-Server=sqldata;Database=Microsoft.Fee.Service.CorporateSponsorIdentityD;User Id=sa;Password=Pass@word}
      - DPConnectionString=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:6379
      - SponsorMvcClient=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5219
      - ScholarshipApiClient=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5205
      - MobileScholarshipAggClient=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5221
      - WebScholarshipAggClient=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5222
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "5227:80"

  sponsor-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - SponsorSpaClient=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5225
      - XamarinCallback=http://${FEE_PROD_EXTERNAL_DNS_NAME_OR_IP}:5201/xamarincallback
      - ConnectionString=${FEE_AZURE_SPONSORIDENTITY_DB:-Server=sqldata;Database=Microsoft.Fee.Service.SponsorIdentityD;User Id=sa;Password=Pass@word}
      - DPConnectionString=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:6379
      - SponsorMvcClient=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5219
      - ScholarshipApiClient=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5205
      - MobileScholarshipAggClient=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5221
      - WebScholarshipAggClient=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5222
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "5201:80"

  student-identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - SpaClient=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5218
      - XamarinCallback=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5202/xamarincallback
      - ConnectionString=${FEE_AZURE_STUDENTIDENTITY_DB:-Server=sqldata;Database=Microsoft.Fee.Service.StudentIdentityD;User Id=sa;Password=Pass@word}
      - DPConnectionString=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:6379
      - MvcClient=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5204
      - ApplyingBasketApiClient=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5206
      - ApplyingApiClient=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5207
      - MobileApplyingAggClient=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5214
      - WebApplyingAggClient=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5215
      - WebhooksApiClient=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5213
      - WebhooksWebClient=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5217
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "5202:80"

  applying-basket-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${FEE_AZURE_REDIS_BASKET_DB:-basketdata}
      - studentidentityUrl=http://student-identity-api
      - StudentIdentityUrlExternal=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5202
      - EventBusConnection=${FEE_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${FEE_SERVICE_BUS_USERNAME}
      - EventBusPassword=${FEE_SERVICE_BUS_PASSWORD}
      - AzureServiceBusEnabled=False
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
      - PATH_BASE=/applying-basket-api
      - GRPC_PORT=81
      - PORT=80
    ports:
      - "5206:80"
      - "9206:81"

  scholarship-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=${FEE_AZURE_SCHOLARSHIP_DB:-Server=sqldata;Database=Microsoft.Fee.Services.ScholarshipDb;User Id=sa;Password=Pass@word}
      - sponsoridentityUrl=http://sponsor-api
      - SponsorIdentityUrlExternal=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5201
      - CorporateSponsorIdentityUrlExternal=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5227
      - PicBaseUrl=${FEE_STORAGE_SCHOLARSHIP_URL}
      - EventBusConnection=${FEE_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${FEE_SERVICE_BUS_USERNAME}
      - EventBusPassword=${FEE_SERVICE_BUS_PASSWORD}
      - AzureStorageAccountName=${FEE_AZURE_STORAGE_SCHOLARSHIP_NAME}
      - AzureStorageAccountKey=${FEE_AZURE_STORAGE_SCHOLARSHIP_KEY}
      - UseCustomizationData=True
      - AzureServiceBusEnabled=False
      - AzureStorageEnabled=False
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - GRPC_PORT=81
      - PORT=80
      - PATH_BASE=/scholarship-api
    ports:
      - "5205:80"
      - "9205:81"

  applying-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${FEE_AZURE_APPLYING_DB:-Server=sqldata;Database=Microsoft.Fee.Services.ApplyingDb;User Id=sa;Password=Pass@word}
      - studentidentityUrl=http://student-identity-api
      - StudentIdentityUrlExternal=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5202
      - EventBusConnection=${FEE_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${FEE_SERVICE_BUS_USERNAME}
      - EventBusPassword=${FEE_SERVICE_BUS_PASSWORD}
      - UseCustomizationData=True
      - AzureServiceBusEnabled=False
      - CheckUpdateTime=30000
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
      - Serilog__MinimumLevel__Override__Microsoft.Fee.BuildingBlocks.EventBusRabbitMQ=Verbose
      - Serilog__MinimumLevel__Override__applying-api=Verbose
      - PATH_BASE=/applying-api
      - GRPC_PORT=81
      - PORT=80
    ports:
      - "5207:80"
      - "9207:81"

  applying-backgroundtasks:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${FEE_AZURE_APPLYING_DB:-Server=sqldata;Database=Microsoft.Fee.Services.ApplyingDb;User Id=sa;Password=Pass@word}
      - EventBusConnection=${FEE_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${FEE_SERVICE_BUS_USERNAME}
      - EventBusPassword=${FEE_SERVICE_BUS_PASSWORD}
      - UseCustomizationData=True
      - AzureServiceBusEnabled=False
      - CheckUpdateTime=30000
      - GracePeriodTime=1
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
      - Serilog__MinimumLevel__Override__Microsoft.Fee.BuildingBlocks.EventBusRabbitMQ=Verbose
    ports:
      - "5211:80"

  payment-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=${FEE_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${FEE_SERVICE_BUS_USERNAME}
      - EventBusPassword=${FEE_SERVICE_BUS_PASSWORD}
      - AzureServiceBusEnabled=False
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - Serilog__MinimumLevel__Override__payment-api.IntegrationEvents.EventHandling=Verbose
      - Serilog__MinimumLevel__Override__Microsoft.Fee.BuildingBlocks.EventBusRabbitMQ=Verbose
    ports:
      - "5212:80"

  webhooks-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${FEE_AZURE_WEBHOOKS_DB:-Server=sqldata;Database=Microsoft.Fee.Services.WebhooksDb;User Id=sa;Password=Pass@word}
      - EventBusConnection=${FEE_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${FEE_SERVICE_BUS_USERNAME}
      - EventBusPassword=${FEE_SERVICE_BUS_PASSWORD}
      - StudentIdentityUrl=http://student-identity-api
      - StudentIdentityUrlExternal=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5202
    ports:
      - "5213:80"

  mobileapplyingapigw:
    volumes:
      - ./ApiGateways/Envoy/config/mobileapplying:/etc/envoy
    ports:
    - "5210:80"
    - "15210:8001"

  mobilescholarshipapigw:
    volumes:
      - ./ApiGateways/Envoy/config/mobilescholarship:/etc/envoy
    ports:
    - "5223:80"
    - "15223:8001"

  webapplyingapigw:
    volumes:
      - ./ApiGateways/Envoy/config/webapplying:/etc/envoy
    ports:
    - "5209:80"
    - "15209:8001"

  webscholarshipapigw:
    volumes:
      - ./ApiGateways/Envoy/config/webscholarship:/etc/envoy
    ports:
    - "5224:80"
    - "15224:8001"

  mobileapplyingagg:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - urls__applyingBasket=http://applying-basket-api
      - urls__scholarship=http://scholarship-api
      - urls__applications=http://applying-api
      - urls__studentIdentity=http://student-identity-api
      - urls__grpcBasket=http://applying-basket-api:81
      - urls__grpcScholarship=http://scholarship-api:81
      - urls__grpcApplying=http://applying-api:81
      - ScholarshipUrlHC=http://scholarship-api/hc
      - ApplyingUrlHC=http://applying-api/hc
      - StudentIdentityUrlHC=http://student-identity-api/hc
      - ApplyingBasketUrlHC=http://applying-basket-api/hc
      - PaymentUrlHC=http://payment-api/hc
      - StudentIdentityUrlExternal=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5202
    ports:
      - "5214:80"

  webapplyingagg:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - urls__applyingBasket=http://applying-basket-api
      - urls__scholarship=http://scholarship-api
      - urls__applications=http://applying-api
      - urls__studentIdentity=http://student-identity-api
      - urls__grpcBasket=http://applying-basket-api:81
      - urls__grpcScholarship=http://scholarship-api:81
      - urls__grpcApplying=http://applying-api:81
      - ScholarshipUrlHC=http://scholarship-api/hc
      - ApplyingUrlHC=http://applying-api/hc
      - StudentIdentityUrlHC=http://student-identity-api/hc
      - ApplyingBasketUrlHC=http://applying-basket-api/hc
      - PaymentUrlHC=http://payment-api/hc
      - StudentIdentityUrlExternal=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5202
    ports:
      - "5215:80"

  mobilescholarshipagg:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - urls__scholarship=http://scholarship-api
      - urls__applications=http://applying-api
      - urls__sponsorIdentity=http://sponsor-api
      - urls__grpcScholarship=http://scholarship-api:81
      - urls__grpcApplying=http://applying-api:81
      - ScholarshipUrlHC=http://scholarship-api/hc
      - ApplyingUrlHC=http://applying-api/hc
      - SponsorIdentityUrlHC=http://sponsor-api/hc
      - CorporateSponsorIdentityUrlHC=http://corporatesponsoridentity-api/hc
      - PaymentUrlHC=http://payment-api/hc
      - SponsorIdentityUrlExternal=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5201
      - CorporateSponsorIdentityUrlExternal=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5227
    ports:
      - "5221:80"

  webscholarshipagg:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - urls__scholarship=http://scholarship-api
      - urls__applications=http://applying-api
      - urls__sponsorIdentity=http://sponsor-api
      - urls__grpcScholarship=http://scholarship-api:81
      - urls__grpcApplying=http://applying-api:81
      - ScholarshipUrlHC=http://scholarship-api/hc
      - ApplyingUrlHC=http://applying-api/hc
      - SponsorIdentityUrlHC=http://sponsor-api/hc
      - CorporateSponsorIdentityUrlHC=http://corporatesponsoridentity-api/hc
      - PaymentUrlHC=http://payment-api/hc
      - SponsorIdentityUrlExternal=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5201
      - CorporateSponsorIdentityUrlExternal=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5227
    ports:
      - "5222:80"

  applying-signalrhub:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=${FEE_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${FEE_SERVICE_BUS_USERNAME}
      - EventBusPassword=${FEE_SERVICE_BUS_PASSWORD}
      - AzureServiceBusEnabled=False
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - studentidentityUrl=http://student-identity-api
    ports:
      - "5216:80"

  webstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HealthChecksUI__HealthChecks__0__Name=WebMVC HTTP Check
      - HealthChecksUI__HealthChecks__0__Uri=http://webmvc/hc
      - HealthChecksUI__HealthChecks__1__Name=Scholarship HTTP Background Check
      - HealthChecksUI__HealthChecks__1__Uri=http://scholarship-api/hc
      - HealthChecksUI__HealthChecks__2__Name=Student Identity HTTP Check
      - HealthChecksUI__HealthChecks__2__Uri=http://student-identity-api/hc
      - HealthChecksUI__HealthChecks__3__Name=Mobile Applying Aggregator HTTP Check
      - HealthChecksUI__HealthChecks__3__Uri=http://mobileapplyingagg/hc
      - HealthChecksUI__HealthChecks__4__Name=Web Applying Aggregator HTTP Check
      - HealthChecksUI__HealthChecks__4__Uri=http://webapplyingagg/hc
      - HealthChecksUI__HealthChecks__5__Name=Applying HTTP Check
      - HealthChecksUI__HealthChecks__5__Uri=http://applying-api/hc
      - HealthChecksUI__HealthChecks__6__Name=Applying Basket HTTP Check
      - HealthChecksUI__HealthChecks__6__Uri=http://applying-basket-api/hc
      - HealthChecksUI__HealthChecks__7__Name=Payments HTTP Check
      - HealthChecksUI__HealthChecks__7__Uri=http://payment-api/hc
      - HealthChecksUI__HealthChecks__8__Name=Applying SignalRHub HTTP Check
      - HealthChecksUI__HealthChecks__8__Uri=http://applying-signalrhub/hc
      - HealthChecksUI__HealthChecks__9__Name=Applying HTTP Background Check
      - HealthChecksUI__HealthChecks__9__Uri=http://applying-backgroundtasks/hc
      - HealthChecksUI__HealthChecks__10__Name=Sponsor Identity HTTP Check
      - HealthChecksUI__HealthChecks__10__Uri=http://sponsor-api/hc
      - HealthChecksUI__HealthChecks__11__Name=Corporate Sponsor Identity HTTP Check
      - HealthChecksUI__HealthChecks__11__Uri=http://corporatesponsoridentity-api/hc
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "5203:80"

  webspa:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - StudentIdentityUrl=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5202
      - ApplyUrl=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5209
      - DPConnectionString=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:6379
      - StudentIdentityUrlHC=http://student-identity-api/hc
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - SignalrHubUrl=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5209
    ports:
      - "5218:80"

  webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ApplyUrl=http://webapplyingapigw
      - StudentIdentityUrl=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5202
      - SignalrHubUrl=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5209
      - StudentIdentityUrlHC=http://student-identity-api/hc
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "5204:80"

  scholarshipmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ApplyUrl=http://webapplyingapigw
      - SponsorIdentityUrl=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5201
      - CorporateSponsorIdentityUrl=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5227
      - SignalrHubUrl=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5216
      - SponsorIdentityUrlHC=http://sponsor-api/hc
      - CorporateSponsorIdentityUrlHC=http://corporatesponsoridentity-api/hc
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "5219:80"

  webhooks-client:
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - Token=6168DB8D-DC58-4094-AF24-483278923590      # Webhooks are registered with this token (any value is valid) but the client won't check it
      - StudentIdentityUrl=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5202
      - CallBackUrl=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5217
      - WebhooksUrl=http://webhooks-api
      - SelfUrl=http://webhooks-client/
    ports:
      - "5217:80"
volumes:
  fee-sqldata:
    external: false
  fee-nosqldata:
    external: false
  fee-basketdata:
    external: false