version: '3.4'

services:

  applying-basket-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${FEE_AZURE_REDIS_BASKET_DB:-basket.data}
      - studentidentityUrl=http://student-identity-api 
      - StudentIdentityUrlExternal=http://${FEE_PROD_EXTERNAL_DNS_NAME_OR_IP}:5202
      - EventBusConnection=${FEE_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${FEE_SERVICE_BUS_USERNAME}
      - EventBusPassword=${FEE_SERVICE_BUS_PASSWORD}
      - AzureServiceBusEnabled=False
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "80"   # The API Gateway redirects and access through the internal port (80).

  scholarship-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${FEE_AZURE_SCHOLARSHIP_DB:-Server=sqldata;Database=Microsoft.Fee.Services.ScholarshipDb;User Id=sa;Password=Pass@word}
      - PicBaseUrl=${FEE_STORAGE_SCHOLARSHIP_URL}
      - EventBusConnection=${FEE_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${FEE_SERVICE_BUS_USERNAME}
      - EventBusPassword=${FEE_SERVICE_BUS_PASSWORD}
      - AzureStorageAccountName=${FEE_AZURE_STORAGE_SCHOLARSHIP_NAME}
      - AzureStorageAccountKey=${FEE_AZURE_STORAGE_SCHOLARSHIP_KEY}
      - UseCustomizationData=True
      - AzureServiceBusEnabled=False
      - AzureStorageEnabled=False
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "80"   # The API Gateway redirects and access through the internal port (80).

  student-identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - XamarinCallback=http://${FEE_PROD_EXTERNAL_DNS_NAME_OR_IP}:5202/xamarincallback      #localhost do not work for UWP login, so we have to use "external" IP always
      - ConnectionString=${FEE_AZURE_IDENTITY_DB:-Server=sqldata;Database=Microsoft.Fee.Services.StudentIdentityDb;User Id=sa;Password=Pass@word}
      - MvcClient=http://${FEE_PROD_EXTERNAL_DNS_NAME_OR_IP}:5204              #Local: You need to open your local dev-machine firewall at range 5200-5210.
      - ApplyingBasketApiClient=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5103
      - ApplyingApiClient=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5102
      - MobileApplyingAggClient=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5120
      - WebApplyingAggClient=http://${FEE_EXTERNAL_DNS_NAME_OR_IP}:5121
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "5202:80"

  applying-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${FEE_AZURE_ORDERING_DB:-Server=sqldata;Database=Microsoft.Fee.Services.ApplyingDb;User Id=sa;Password=Pass@word}
      - studentidentityUrl=http://student-identity-api              #Local: You need to open your local dev-machine firewall at range 5100-5110.
      - StudentIdentityUrlExternal=http://${FEE_PROD_EXTERNAL_DNS_NAME_OR_IP}:5202
      - EventBusConnection=${FEE_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${FEE_SERVICE_BUS_USERNAME}
      - EventBusPassword=${FEE_SERVICE_BUS_PASSWORD}
      - UseCustomizationData=True
      - AzureServiceBusEnabled=False
      - CheckUpdateTime=30000
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "80"   # The API Gateway redirects and access through the internal port (80).

  applying-backgroundtasks:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${FEE_AZURE_APPLYING_DB:-Server=sqldata;Database=Microsoft.Fee.Services.ApplyingDb;User Id=sa;Password=Pass@word}
      - EventBusConnection=${FEE_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${FEE_SERVICE_BUS_USERNAME}
      - EventBusPassword=${FEE_SERVICE_BUS_PASSWORD}
      - UseCustomizationData=True
      - AzureServiceBusEnabled=False
      - CheckUpdateTime=30000
      - GracePeriodTime=1
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "5211:80"

  webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ApplicationUrl=http://webapplyingapigw
      - StudentIdentityUrl=http://10.0.75.1:5202
      - ScholarshipUrlHC=http://scholarship-api/hc
      - ApplyingUrlHC=http://applying-api/hc
      - StudentIdentityUrlHC=http://student-identity-api/hc
      - ApplyingBasketUrlHC=http://applying-basket-api/hc
      - PaymentUrlHC=http://payment-api/hc
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "5204:80"

  webstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ScholarshipUrl=http://scholarship-api/hc
      - ApplyingUrl=http://applying-api/hc
      - ApplyingBasketUrl=http://applying-basket-api/hc
      - StudentIdentityUrl=http://student-identity-api/hc
      - PaymentUrl=http://payment-api/hc
      - mvc=http://webmvc/hc
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "5203:80"

  payment-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=${FEE_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${FEE_SERVICE_BUS_USERNAME}
      - EventBusPassword=${FEE_SERVICE_BUS_PASSWORD}
      - AzureServiceBusEnabled=False
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "80"   # The API Gateway redirects and access through the internal port (80).

  sqldata:
    user: root
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"    # Important: In a production environment your should remove the external port

  nosqldata:
    ports:
      - "27017:27017"  # Important: In a production environment your should remove the external port

  basket.data:
    ports:
      - "6379:6379"    # Important: In a production environment your should remove the external port

  rabbitmq:
    ports:
      - "15672:15672"  # Important: In a production environment your should remove the external port
      - "5672:5672"    # Important: In a production environment your should remove the external port

  mobileapplyingapigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - StudentIdentityUrl=http://student-identity-api              #Local: You need to open your local dev-machine firewall at range 5200-5210.
    ports:
      - "5210:80"   # Important: In a production environment your should remove the external port (5200) kept here for microservice debugging purposes.
                    # The API Gateway redirects and access through the internal port (80).
    volumes:
      - ./ApiGateways/Mobile.Bff.Applying/apigw:/app/configuration

  webapplyingapigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - StudentIdentityUrl=http://student-identity-api       #Local: You need to open your local dev-machine firewall at range 5200-5210.
    ports:
      - "5209:80"   # Important: In a production environment your should remove the external port (5202) kept here for microservice debugging purposes.
                    # The API Gateway redirects and access through the internal port (80).
    volumes:
      - ./ApiGateways/Web.Bff.Applying/apigw:/app/configuration

  mobileapplyingagg:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - urls__applyingBasket=http://applying-basket-api
      - urls__scholarship=http://scholarship-api
      - urls__applications=http://applying-api
      - urls__studentIdentity=http://student-identity-api              #Local: You need to open your local dev-machine firewall at range 5100-5110.
    ports:
      - "80"   # Important: In a production environment your should remove the external port (5120) kept here for microservice debugging purposes.
                    # The API Gateway redirects and access through the internal port (80).

  webapplyingagg:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - urls__applyingBasket=http://applying-basket-api
      - urls__scholarship=http://scholarship-api
      - urls__applications=http://applying-api
      - urls__studentIdentity=http://student-identity-api             #Local: You need to open your local dev-machine firewall at range 5100-5110.
    ports:
      - "80"   # Important: In a production environment your should remove the external port (5121) kept here for microservice debugging purposes.
                    # The API Gateway redirects and access through the internal port (80).