FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src
COPY ["BuildingBlocks/EventBus/EventBus/EventBus.csproj", "BuildingBlocks/EventBus/EventBus/"]
COPY ["BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.csproj", "BuildingBlocks/EventBus/EventBusRabbitMQ/"]
COPY ["BuildingBlocks/EventBus/EventBusServiceBus/EventBusServiceBus.csproj", "BuildingBlocks/EventBus/EventBusServiceBus/"]
COPY ["BuildingBlocks/EventBus/IntegrationEventLogEF/IntegrationEventLogEF.csproj", "BuildingBlocks/EventBus/IntegrationEventLogEF/"]
COPY ["BuildingBlocks/WebHostCustomization/WebHost.Customization/WebHost.Customization.csproj", "BuildingBlocks/WebHostCustomization/WebHost.Customization/"]
COPY ["Services/Applying/Applying.Domain/Applying.Domain.csproj", "Services/Applying/Applying.Domain/"]
COPY ["Services/Applying/Applying.Infrastructure/Applying.Infrastructure.csproj", "Services/Applying/Applying.Infrastructure/"]
COPY ["Services/Applying/Applying.API/Applying.API.csproj", "Services/Applying/Applying.API/"]
COPY ["NuGet.config", "NuGet.config"]

RUN dotnet restore Services/Applying/Applying.API/Applying.API.csproj
COPY . .
WORKDIR /src/Services/Applying/Applying.API
RUN dotnet build -c $BUILD_CONFIGURATION

ENTRYPOINT ["dotnet", "run", "--no-build", "--no-launch-profile", "-c", "$BUILD_CONFIGURATION", "--"]